# Tên ứng dụng
spring.application.name=affiliate

# Cổng khởi chạy ứng dụng
server.port=8080

# Tắt cache Thymeleaf trong môi trường phát triển (Local Development) để cập nhật giao diện nóng lập tức
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Định dạng mã hóa ký tự UTF-8 cho Thymeleaf để hiển thị tiếng Việt chính xác
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html;charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Cấu hình Kết nối Cơ sở Dữ liệu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/affiliate_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=15112005!Nah
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

